module.exports = {
	"address": "Address",
	"admin": "Admin",
	"announcements": "Announcement",
	"appclients": "Appclient",
	"attributes": "Attribute",
	"business-hours": "BusinessHour",
	"carts": "Cart",
	"categories": "Category",
	"category-attributes": "CategoryAttribute",
	"countries": "Country",
	"coupons": "Coupon",
	"coupon-categories": "CouponCategory",
	"coupon-excluded-categories": "CouponExcludedCategory",
	"coupon-excluded-products": "CouponExcludedProduct",
	"coupon-products": "CouponProduct",
	"currencies": "Currency",
	"discounts": "Discount",
	"discussion-boards": "DiscussionBoard",
	"discussion-board-details": "DiscussionBoardDetail",
	"email-templates": "EmailTemplate",
	"featured-products": "FeaturedProduct",
	"global-settings": "GlobalSetting",
	"mails":"Mail",
	"marketplaces": "Marketplace",
	"marketplace-types": "MarketplaceType",
	"marketplace-products": "MarketplaceProduct",
	"notification-settings":"NotificationSetting",
	"order-items": "OrderItem",
	"order-payments": "OrderPayment",
	"order-payment-escrows": "OrderPaymentEscrow",
	"order-vendors":"OrderVendor",
	"order-vendor-payouts":"OrderVendorPayout",
	"orders": "Order",
	"payment-settings": "PaymentSetting",
	"plans": "Plan",
	"plan-limits": "PlanLimit",
	"plan-marketplaces": "PlanMarketplace",
	"products": "Product",
	"product-ads-settings": "ProductAdsSetting",
	"product-attributes": "ProductAttribute",
	"product-medias": "ProductMedia",
	"reviews":"Review",
	"star-rating":"Review",
	"regions": "Region",
	"shippings": "Shipping",
	"states": "State",
	"sub-categories": "SubCategory",
	"subscriptions": "Subscription",
	"subscription-sales": "SubscriptionSales",
	"talks": "Talk",
	"talk-settings": "TalkSetting",
	"talk-threads": "TalkThread",
	"talk-thread-users": "TalkThreadUsers",
	"terms-and-cond":"TermsAndCond",
	"taxes": "Tax",
	"tickets": "Ticket",
	"ticket-threads": "TicketThread",
	"timezones": "Timezone",
	"users": "User",
	"user-plan": "UserPlan",
	"user-mails": "UserMail",
	"user-tokens": "UserToken",
	"vendor": "Vendor",
	"vendor-followers": "VendorFollower",
	"vendor-notification": "VendorNotification",
	"vendor-notification-settings": "VendorNotificationSetting",
	"vendor-plans": "VendorPlan",
	"vendor-sales": "VendorSales",
	"vendor-shipping-locations": "VendorShippingLocation",
	"vendor-verifications": "VendorVerification",
	"wish-list": "WishList",
	"order-items-overview": "OrderItemsOverview"
}